# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c79ebd3fd125291d30e6dae374af479e321d4e2813f6a9d50c547b0509af174ab45cdf0b05bb25292a5ab26a0777ff39757a5f0369c4e0f590714abf2cca427

test:
  secret_key_base: 4e0c16cfa9f97dae96c6712647beb6266024704c8ea1201f938591266b3e0c42b8b68e3b92bf8e573f65ea97127005d197583342c3fb4b40658095e9d72d875b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
